config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 resources :posts do
 	resources :comments
 end


 root "posts#index"

 get '/about', to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: {minimum: 5}
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about 
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
	@post = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def create
	@post = Post.new (post_params)

	if @post.save
	redirect_to @post
		else
			render 'new'
		end
	end

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to root_path
	end

	private 
	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago</p>
	</div>

	<% if user_signed_in? %>
	<p><%= link_to 'Delete', [comment.post, comment], 
					method: :delete,
					class: "button",
					data: {confirm: "are you sure?" } %>
					</p>
		<% end%>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
<p>
<%= f.label :name %> <br>
<%= f.text_field :name %>
</p>

<p>
<%= f.label :body %> <br>
<%= f.text_area :body %>
</p>
<br>
<p>
<%= f.submit %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Blog</title>

  <%= stylesheet_link_tag  "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
   <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
</head>
<body>

<div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
               		
		
                 <li><%= link_to "My Blog", root_path %></li>
        		 <li><%= link_to "About Me", about_path %></li>
                	<br>
            <li><a href="http://mauricemcerlean.com">My Website</a></li>
			<li><a href="https://twitter.com/MauriceMcErlean">Twitter</a></li>
			<li><a href="https://dribbble.com/MauriceMcErlean">Dribble</a></li>
			<li><a href="https://github.com/mauricemcerlean">Github</a></li>
			<li><a href="mailto:mauricemcerlean@hotmail.co.uk">Email</a></li>


			<br><br><br>
			<% if !user_signed_in? %>
		<li class ="adminlogin">Admin Login</li>
		<% end %>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->


        <!-- /#page-content-wrapper -->

    </div>
    <!-- /#wrapper -->

		<div id ="main_content">
			<div id ="header">
				<% if current_page?(root_path) %>
				<p>All Posts</p>
			<% elsif current_page?(about_path) %>
				<p>About</p>
			<% else %>
				<%= link_to "Back to All Posts", root_path %>
			<% end %>

			<% if user_signed_in? %>
				<div class ="buttons">
					<button class="button"><%= link_to "New Post", new_post_path %></button>
					<button class ="button">Log Out</button>
				</div>
				<% end %>
				</div>

		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert") %>
		<% end %>

		<%= yield %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
	<div id="profile_image">
		<img src = "http://www.mauricemcerlean.com/img/header/me.png" style="text-align: left" width="20%">
	</div>

	<div id="content">
		<h1>Welcome to my blog!</h1>
		<p>My name is Maurice and I'm from Ballymena in Northern Ireland and I'm currently a second year student studying Interactive Multimedia Design at the University of Ulster in Jordanstown. I decided that this was the right career move for me because I am passionate about coding and design.</p>
		
		<p>I like to be creative and as someone who develops websites, this is very important because it gives me a chance to create interesting websites.</p>

		<p>Creating websites is something I really enjoy, and I love that I can add my passion for Photography into my skill set.</p>
	</div>
</div>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
<div id ="errors">
<h2><%= pluralize(@post.errors.count, "error") %> Couldnt post, please check post</h2>
<ul>
<% @post.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<p>
<%= f.label :title %><br>
<%= f.text_field :title%>
</p
	

<p>
<%= f.label :body %><br>
<%= f.text_area :body %>
</p>

<p>
<%= f.submit%>
</p>

<% end %>

app/views/posts/edit.html.erb
<div id "page_wrapper">
<h1>Edit Post</h1>


<%= render 'form'%>
</div>

app/views/posts/index.html.erb
<% @post.each do |post| %>
<div class ="post_wrapper">
	<h2 class ="title"> <%= link_to post.title, post %></h2>

	<p class ="date"> <%= post.created_at.strftime("%B, %d, %Y")%></p>
	</div>

<% end %>

app/views/posts/new.html.erb
<div id ="page_wrapper">
<h1>New Post</h1>

<%= render 'form'%>

</div>

app/views/posts/show.html.erb
<div id="post_content">
	<h1 class="title">
	<%= @post.title %>
	</h1>

<p class ="date">
Submitted <%= time_ago_in_words(@post.created_at) %> ago
<% if user_signed_in? %>
| <%= link_to 'Edit', edit_post_path(@post)%>
| <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'} %>
<%end %>
</p>

	<p class="body">
	<%= @post.body %>
	</p>

<div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%= render @post.comments %>

		<h3>Add a comment:</h3>
		<%= render "comments/form" %>
	</div>
</div>